### ISSUE TITLE
error after upgrade to Debian testing

### ISSUE THREAD

**Issue by LaPriWa** [fadecut/fadecut#32]
Hello, I used fadecut a lot on Debian 8 "Jessie" and I loved it.
Unfortunately, after upgrading Debian to "Testing"., I receive the following error every time I start fadecut:

```
13:24:27 Info:     Loading profile file(s):
13:24:27           /home/philipp/.fadecut/profiles/DroneZone
13:24:27 Success:  /usr/bin/streamripper started pid=10190
sed: -e expression #1, char 2: unterminated `s' command
```

I spent some time reading the sourcecode but I am not able to find the reason for this error.

**Comment by mgafner** [comment]
Thanks for the issue. I am going to test this out today evening.

**Comment by mgafner** [comment]
okay, i found the bug. In the line 1127 the `^M` in the first sed command caused the script to insert a linefeed. 

`StreamInfo=$(tail -1 $LOGDIR/fadecutstream-$PID.log | sed -e 's/^M/\n/g' | tail -1 | sed -e 's/ \[.*$//g')`

On earlier versions of streamripper and bash this was needed. On Ubuntu 16.04 it still works. On Debian testing it does not work anymore. It produces the error because it is interpreting the oneliner as two lines. Right now, Ubuntu 16.04 and Debian Testing have the same versions of Streamripper (v 1.64.6) and Bash (4.3.46(1)) installed. I have no clue why they behave different. Now I changed the code to

`StreamInfo=$(tail -1 $LOGDIR/fadecutstream-$PID.log | sed -e 's/ \[.*$//g')`

this works on both distributions.

@micressor: could you please upload an updated debian packet?

Thanks to @LaPriWa for opening the issue! You may download the script [right here from github](https://raw.githubusercontent.com/fadecut/fadecut/master/fadecut) until the new debian packet is distributed.

**Comment by LaPriWa** [comment]
Thank you very much! It works perfectly.

**Comment by oesel** [comment]
Hi,

I get the same error:
sed: -e Ausdruck #1, Zeichen 2: Nicht beendeter `s'-Befehl

But can I solve this problem without changing the program code?
I'm only a user, not a programmer and I had no luck by compiling software in the past! 

But I really liked fadecut and I want to use it on...

Thanks a lot in advance

**Comment by mgafner** [comment]
Hi @oesel 

We fixed this problem already here on github. Maybe the new version is not yet in debian. May I ask you to download the current version from here: https://raw.githubusercontent.com/fadecut/fadecut/master/fadecut 

try with that one.

best regards

**Comment by mgafner** [comment]
do you have any feedbacks @oesel ?

**Comment by oesel** [comment]
Hi mgafner,

sorry, I was quite busy.
Well, thanks a lot for your reply, but I'm sorry, I have never made a DEB-file by myself.
I followed the instruction step by step, but when I type in

> docker build -t debian-testing .

I get this error message:

> FATA[0000] Cannot locate Dockerfile: Dockerfile

What is my fault?
And please let me ask you: is there no final DEB-file ready for download?

**Comment by LaPriWa** [comment]
Hello oesel,

you could clone the repository and copy the fadecut file into the directory `/opt/`. Afterwards make a symbolic link, e.g. `$ sudo ln -s /opt/fadecut /usr/local/bin/fadecut`.
Last but not least create a profile: `$ fadecut -c ProfileName`.

Sincerely yours
LaPriWa

**Comment by oesel** [comment]
Hi LaPriWa,

first of all I uninstalled my old fadecut with
`sudo apt-get purge fadecut`
That works.

After that I downloaded the [ZIP-file](https://github.com/fadecut/fadecut/archive/master.zip), unzipped it on my computer and copied all files into the /opt Folder, so finally to /opt/fadecut
Secondary I copied my old profile-folder into /opt/fadecut too.

After that I typed
 `sudo ln -s /opt/fadecut /usr/local/bin/fadecut`

When I try to create a new profile or use an old profile, I get the following error message:
`bash: /usr/bin/fadecut: Ist ein Verzeichnis `- (it's a folder)

I have no clue, what's my mistake.
And I'm wondering myself, because it is named` /usr/bin/fadecut`
but I made a symbolic link to `/usr/local/bin/fadecut`

And please let me ask you, if it's correct, that I don't have to compile the files I downloaded [here from github](https://github.com/fadecut/fadecut/archive/master.zip)?

Thank you.

**Comment by micressor** [comment]
I would suggest
`apt-get install fadecut`
`wget https://raw.githubusercontent.com/fadecut/fadecut/master/fadecut -O /usr/bin/fadecut`
to fix this (for the moment) in a fast way.

**Comment by oesel** [comment]
Hi micressor,

now I have the next error:

```
> fadecut -p testprofil -r
> 22:00:20 Info:     Loading profile: /home/oesel/.fadecut/profiles/testprofil
> 22:00:20 Error:    Program mediainfo not installed or not in PATH
```

OMG, a neverending story?

**Comment by LaPriWa** [comment]
Hello oesel,

you have to install the mediainfo package:

`$ sudo apt install mediainfo` or `$ sudo apt-get install mediainfo`.

**Comment by micressor** [comment]
Fix is on the way #53 to debian.

**Comment by micressor** [comment]
@oesel You can use now the latest [Dockerfile](https://raw.githubusercontent.com/fadecut/fadecut/master/Dockerfile) and [instructions](https://github.com/fadecut/fadecut#dockerfile). That should work. There is no DEB-File at the moment. Besides I work on a Dockerfile for the deb build.

**Comment by micressor** [comment]
@LaPriWa Is this still an issue? Please note: [fadecut 0.2.1](https://tracker.debian.org/fadecut) just released to debian unstable.

**Comment by ka223** [comment]
Is it still broken on debian repository?
Release:	9.4
Codename:	stretch
Version fadecut         0.1.4-1.1

**Comment by micressor** [comment]
@ka223 Yes, it is [fixed](https://tracker.debian.org/pkg/fadecut) and currently in debian testing.
